### ISSUE TITLE
build of OC4VM doesn't include AMD

### ISSUE THREAD

**Issue by ashleyw-gh** [DrDonk/OC4VM#1]
Just tried to use a running OS12 VM on an AMD ESXi host to build the OC4VM package.
It built fine but I can only see Intel template folders. In the documentation it says "To create a new virtual machine copy either the Intel or AMD template to a new folder".
It would be great if you have a chance to add whatever is needed to generate the AMD template folders.
Also when I registered the vmx in the templates/intel-default into esxi, when i tried to start it up, I got an "invalid disk type 2" message so i had to run the following on the esxi console session in the directory of the uploaded template.
```
vmkfstools -i opencore.vmdk opencore2.vmdk
vmkfstools -i macos.vmdk macos2.vmdk
```
and then add those disk back to the VM. but then I predictably get a message;
"Failed - Feature 'cpuid.intel' was 0, but must be at least 1."

which I guess is expected due to the lack of an AMD template folder?

keep up the great work by the way! This has the potential to make things workable to a lot of people again (especially if the binary releases including AMD could also be published).
thanks.

**Comment by startergo** [comment]
To enable AMD builds you have to manipulate `oc4vm.toml`.
Look under `AMD` sections and change: `BUILD = '0'` to `BUILD = '1'` in the section you would like to be included in the build.

**Comment by DrDonk** [comment]
It does not support AMD even though in the builds.

**Comment by startergo** [comment]
@DrDonk Can you include `WHPX` and [`AEHD`](https://github.com/MateuszKrawczuk/qemu/tree/master_wip_aehd) acceleration options?

**Comment by DrDonk** [comment]
I can. I took a break from this, and will be looking to restart in the New Year.

**Comment by startergo** [comment]
Great. See here:
https://www.reddit.com/r/androiddev/comments/166jz0m/comment/jyl3ix7/
Just FYI I have tested AEHD. For Linux VM is great, but I can't still get macOS to boot there. it crashes on corecrypto.

**Comment by DavidBerdik** [comment]
> It does not support AMD even though in the builds.

If you'd like to revisit testing this with me, just let me know!

**Comment by DrDonk** [comment]
> If you'd like to revisit testing this with me, just let me know!

Sure thing. I took a step back on the project as felt it was not progressing. I am now using it to run QEMU and Intel macOS on Apple Silicon which is why I have started looking into the idea again.

**Comment by DavidBerdik** [comment]
> I am now using it to run QEMU and Intel macOS on Apple Silicon which is why I have started looking into the idea again.

I'm not sure if I understand what the point would be of running x86 macOS on Apple Silicon? What does the x86 version of macOS have that the Apple Silicon version doesn't?

**Comment by DavidBerdik** [comment]
Fair enough! Anyway, if you come up with anything you want me to test, you know my e-mail!

**Comment by DrDonk** [comment]
Closing this for now. Please discuss on the Discussions. I will setup some sub folders for Intel, AMD and General conversations.
